Parameters:
  RepositoryName:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  MasterContainerUri:
    Value: !Sub
      - ${RepositoryUri}:master
      - RepositoryUri: !GetAtt Repository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-MasterContainerUri
